// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxqFt5R-9WFzUw0po_qY1LKtLuweaiqmM',
    appId: '1:825353246981:web:9652ab1ce3bdbf0a353f6c',
    messagingSenderId: '825353246981',
    projectId: 'group-project-666b6',
    authDomain: 'group-project-666b6.firebaseapp.com',
    storageBucket: 'group-project-666b6.firebasestorage.app',
    measurementId: 'G-87SX2PJ2S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATVxy2JZtwxfbRt7HdIccCDXz6e86vFtI',
    appId: '1:825353246981:android:9b7ae4a8e967a056353f6c',
    messagingSenderId: '825353246981',
    projectId: 'group-project-666b6',
    storageBucket: 'group-project-666b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHUvnGttsSmFImlDd0NjMosBEK7vZY8HY',
    appId: '1:825353246981:ios:f202c83f6ad651cb353f6c',
    messagingSenderId: '825353246981',
    projectId: 'group-project-666b6',
    storageBucket: 'group-project-666b6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHUvnGttsSmFImlDd0NjMosBEK7vZY8HY',
    appId: '1:825353246981:ios:f202c83f6ad651cb353f6c',
    messagingSenderId: '825353246981',
    projectId: 'group-project-666b6',
    storageBucket: 'group-project-666b6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxqFt5R-9WFzUw0po_qY1LKtLuweaiqmM',
    appId: '1:825353246981:web:e72dfce71dafd546353f6c',
    messagingSenderId: '825353246981',
    projectId: 'group-project-666b6',
    authDomain: 'group-project-666b6.firebaseapp.com',
    storageBucket: 'group-project-666b6.firebasestorage.app',
    measurementId: 'G-0MDH8E2QJM',
  );
}
